/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as StatsRouteImport } from './app/routes/stats'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as QuizCategoryRouteImport } from './app/routes/quiz.$category'
import { Route as CategoryCategoryIdRouteImport } from './app/routes/category.$categoryId'
import { Route as QuizCategoryPlayRouteImport } from './app/routes/quiz.$category.play'

const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizCategoryRoute = QuizCategoryRouteImport.update({
  id: '/quiz/$category',
  path: '/quiz/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoryCategoryIdRoute = CategoryCategoryIdRouteImport.update({
  id: '/category/$categoryId',
  path: '/category/$categoryId',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizCategoryPlayRoute = QuizCategoryPlayRouteImport.update({
  id: '/play',
  path: '/play',
  getParentRoute: () => QuizCategoryRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/stats': typeof StatsRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/quiz/$category': typeof QuizCategoryRouteWithChildren
  '/quiz/$category/play': typeof QuizCategoryPlayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/stats': typeof StatsRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/quiz/$category': typeof QuizCategoryRouteWithChildren
  '/quiz/$category/play': typeof QuizCategoryPlayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/stats': typeof StatsRoute
  '/category/$categoryId': typeof CategoryCategoryIdRoute
  '/quiz/$category': typeof QuizCategoryRouteWithChildren
  '/quiz/$category/play': typeof QuizCategoryPlayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/stats'
    | '/category/$categoryId'
    | '/quiz/$category'
    | '/quiz/$category/play'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/stats'
    | '/category/$categoryId'
    | '/quiz/$category'
    | '/quiz/$category/play'
  id:
    | '__root__'
    | '/'
    | '/stats'
    | '/category/$categoryId'
    | '/quiz/$category'
    | '/quiz/$category/play'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  StatsRoute: typeof StatsRoute
  CategoryCategoryIdRoute: typeof CategoryCategoryIdRoute
  QuizCategoryRoute: typeof QuizCategoryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$category': {
      id: '/quiz/$category'
      path: '/quiz/$category'
      fullPath: '/quiz/$category'
      preLoaderRoute: typeof QuizCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$categoryId': {
      id: '/category/$categoryId'
      path: '/category/$categoryId'
      fullPath: '/category/$categoryId'
      preLoaderRoute: typeof CategoryCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz/$category/play': {
      id: '/quiz/$category/play'
      path: '/play'
      fullPath: '/quiz/$category/play'
      preLoaderRoute: typeof QuizCategoryPlayRouteImport
      parentRoute: typeof QuizCategoryRoute
    }
  }
}

interface QuizCategoryRouteChildren {
  QuizCategoryPlayRoute: typeof QuizCategoryPlayRoute
}

const QuizCategoryRouteChildren: QuizCategoryRouteChildren = {
  QuizCategoryPlayRoute: QuizCategoryPlayRoute,
}

const QuizCategoryRouteWithChildren = QuizCategoryRoute._addFileChildren(
  QuizCategoryRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  StatsRoute: StatsRoute,
  CategoryCategoryIdRoute: CategoryCategoryIdRoute,
  QuizCategoryRoute: QuizCategoryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
